# Welcome to Jekyll!
#

# Site settings
title: Robert Camacho <br /> for District Leader in the 54th <br />
abbreviated_title: Robert Camacho
description: |
  <em>“You know what time it is, it’s MACHO time”<em/>
owner: Robert Camacho # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://camachofor54.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:camachofor54@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
